SAMPLES:
- Bulk-RNA_S2_B1
- Bulk-RNA_S2_B2
- Bulk-RNA_S1_B1
- Bulk-RNA_S1_B2

subfamilies:
- L1HS
- L1PA2
- L1PA3
- L1PA4
- L1PA5
- L1PA6
- L1PA7

H3K9_matrix:
- H3K9me3/H3K9_S1
- H3K9me3/H3K9_S2
- H3K9me3/H3K9_control_S1
- H3K9me3/H3K9_control_S2

H3K4me3_matrix:
- H3K4me/H3K4me3_S1
- H3K4me/H3K4me3_S2
- H3K4me/H3K4me_control_S1
- H3K4me/H3K4me_control_S2

H3K4me1_matrix:
- H3K4me/H3K4me1_S1
- H3K4me/H3K4me1_S2
- H3K4me/H3K4me_control_S1
- H3K4me/H3K4me_control_S2

H3K27_matrix:
- H3K27me3/H3K27me3_S1-T1
- H3K27me3/H3K27me3_S1-T2
- H3K27me3/H3K27me3_S2-T1
- H3K27me3/H3K27me3_S2-T2
- H3K27me3/H3K27me3_control_S1
- H3K27me3/H3K27me3_control_S2

matrices:
- H3K9
- H3K4me3
- H3K4me1
- H3K27

L1s:
- L1HS
- L1PA2
- L1PA3
- L1PA4
- L1PA5
- L1PA6
- L1PA7

HERVs:
- HERV

Chimp:
- S1_B1
- S1_B2
- S2_B1
- S2_B2
